version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment with a docker
    docker:
        #Specify the node version/image
      - image: cimg/node:18.0.0
      working_directory: ~/repo
      
    steps:
        #Access the github code
      - checkout
      
        #Do dependencie stuff
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum"package.json" }}
            - v1-dependencies-
          
      - run: npm install
      -run:
        name: Run npm tests
        command: npm test
      -run:
        name: Run npm build
        command: npm run build

      -save_cache:
        paths:
          -node_modules
        key: v1-dependencies-{{ checksum "package.json" }}